[tool.isort]
profile = "black"
force_sort_within_sections = true
combine_as_imports = true

# Currently not supoprted by VS Code....
#[tool.pylint.'MESSAGES CONTROL']
#disable = "unsubscriptable-object,duplicate-code"