[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.poetry]
authors = ["Ludeeus <ludeeus@ludeeus.dev>"]
classifiers = [
  "Intended Audience :: Developers",
  "Natural Language :: English",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
description = "One version package to rule them all, One version package to find them, One version package to bring them all, and in the darkness bind them."
exclude = ['**/__pycache__']
include = ["awesomeversion", "awesomeversion.*", "LICENCE.md"]
keywords = ["calver", "semver", "0ver", "version", "pep440", "buildver"]
license = "MIT"
maintainers = ["Ludeeus <ludeeus@ludeeus.dev>"]
name = "awesomeversion"
readme = "README.md"
repository = "https://github.com/ludeeus/awesomeversion"
version = "0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^22.3"
isort = "^5.10.1"
mypy = "^0.942"
pylint = "^2.13.7"
pytest = "^7.1.2"
pytest-cov = "^3.0.0"

[tool.isort]
combine_as_imports = true
force_sort_within_sections = true
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
disable = "unsubscriptable-object,duplicate-code"


[tool.coverage.run]
source = ["awesomeversion"]
omit = ["setup.py", "tests/*"]

[tool.coverage.report]
exclude_lines = ["if TYPE_CHECKING:"]