#!/bin/sh

# script/coverage: Run tests and generate coverage reports

set -e

cd "$(dirname "$0")/.."

echo "==> Running coverage analysis..."
uv run --dev pytest tests --timeout=10 -rxf -x -v -l --cov=./ --cov-report=xml > /dev/null
uv run --dev coverage report

echo "==> Coverage analysis completed!"
